set_property PACKAGE_PIN N11 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN E6 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {Scan_Sig[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Scan_Sig[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Scan_Sig[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMG_Data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMG_Data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMG_Data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMG_Data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMG_Data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMG_Data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMG_Data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMG_Data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RSTn]
set_property PACKAGE_PIN N11 [get_ports CLK]
set_property PACKAGE_PIN E6 [get_ports RSTn]

set_property PACKAGE_PIN T8 [get_ports {Scan_Sig[2]}]
set_property PACKAGE_PIN P10 [get_ports {Scan_Sig[1]}]
set_property PACKAGE_PIN T9 [get_ports {Scan_Sig[0]}]
set_property PACKAGE_PIN T10 [get_ports {SMG_Data[0]}]
set_property PACKAGE_PIN K13 [get_ports {SMG_Data[1]}]
set_property PACKAGE_PIN P11 [get_ports {SMG_Data[2]}]
set_property PACKAGE_PIN R11 [get_ports {SMG_Data[3]}]
set_property PACKAGE_PIN R10 [get_ports {SMG_Data[4]}]
set_property PACKAGE_PIN N9 [get_ports {SMG_Data[5]}]
set_property PACKAGE_PIN K12 [get_ports {SMG_Data[6]}]
set_property PACKAGE_PIN P9 [get_ports {SMG_Data[7]}]
