set_property PACKAGE_PIN N11 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN B7 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports SD_clk]
set_property IOSTANDARD LVCMOS33 [get_ports SD_cs]
set_property IOSTANDARD LVCMOS33 [get_ports SD_datain]
set_property IOSTANDARD LVCMOS33 [get_ports SD_dataout]
set_property PACKAGE_PIN J5 [get_ports SD_cs]
set_property PACKAGE_PIN K5 [get_ports SD_datain]
set_property PACKAGE_PIN E6 [get_ports SD_clk]
set_property PACKAGE_PIN B5 [get_ports SD_dataout]
